name: Main workflow

on: push

jobs:
  default_routine:
    name: Default routine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run all tests
        run: python3 -m unittest discover -s tests/ -p '*Test.py'

      # - name: Vulnerability scan
      #   uses: MeterianHQ/meterian-github-action@v1.0.10
      #   env:
      #       METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}

  release_draft:
    if: github.ref_name == 'main'
    name: Release draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binary
        run: |
             pip3 install pyinstaller==4.8
             pyinstaller --paths=src --name=meterian-pr --onefile src/Main.py

      - name: Draft release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
             VERSION=$(./dist/meterian-pr --version)
             gh release create $VERSION --generate-notes --draft dist/meterian-pr
