name: Main workflow

on: push

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test_routine:
    name: Test routine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run all tests
        run: |
             pip3 install pipenv
             pipenv install
             pipenv run python3 -m unittest discover -s tests/ -p '*Test.py'

      - name: Vulnerability scan
        uses: MeterianHQ/meterian-github-action@v1.0.10
        env:
            METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}

  build_and_release:
    needs: test_routine
    name: "Build & draft release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binary
        run: |
             pip3 install -r requirements.txt
             pip3 install pyinstaller==4.8
             pyinstaller --paths=src --name=meterian-pr --onefile src/Main.py
             chmod +x dist/meterian-pr
             ./dist/meterian-pr --version

      - name: Draft release
        if: github.ref_name == 'main'
        run: |
             VERSION=$(./dist/meterian-pr --version)
             gh release create $VERSION --generate-notes --draft dist/meterian-pr
